### ISSUE TITLE
Failed to build `pyaudio==0.2.14`

### ISSUE THREAD

**Issue by britannio** [kwindla/pipecat-dictation#5]
Hello, I'm running in to the following error when setting up the project

```
➜  pipecat-dictation git:(main) uv run bot-realtime-api.py
Using CPython 3.13.5
Creating virtual environment at: .venv
      Built pipecat-ai-small-webrtc-prebuilt==1.0.0
      Built pytweening==1.2.0
      Built pyautogui==0.9.54
      Built pyscreeze==1.0.1
      Built pyperclip==1.9.0
      Built pymsgbox==1.0.9
      Built pyrect==0.2.0
      Built mouseinfo==0.1.3
      Built pygetwindow==0.0.9
  × Failed to build `pyaudio==0.2.14`
  ├─▶ The build backend returned an error
  ╰─▶ Call to `setuptools.build_meta.build_wheel` failed (exit status: 1)

      [stdout]
      running bdist_wheel
      running build
      running build_py
      creating build/lib.macosx-11.0-arm64-cpython-313/pyaudio
      copying src/pyaudio/__init__.py -> build/lib.macosx-11.0-arm64-cpython-313/pyaudio
      running build_ext
      building 'pyaudio._portaudio' extension
      creating build/temp.macosx-11.0-arm64-cpython-313/src/pyaudio
      cc -fno-strict-overflow -Wsign-compare -Wunreachable-code -DNDEBUG -g -O3 -Wall -arch arm64 -mmacosx-version-min=11.0 -Wno-nullability-completeness -Wno-expansion-to-defined
      -Wno-undef-prefix -fPIC -DMACOS=1 -I/usr/local/include -I/usr/include -I/opt/homebrew/include -I/Users/britannio/.cache/uv/builds-v0/.tmpm14POP/include
      -I/Users/britannio/.local/share/uv/python/cpython-3.13.5-macos-aarch64-none/include/python3.13 -c src/pyaudio/device_api.c -o build/temp.macosx-11.0-arm64-cpython-313/src/pyaudio/device_api.o

      [stderr]
      /Users/britannio/.cache/uv/builds-v0/.tmpm14POP/lib/python3.13/site-packages/setuptools/dist.py:759: SetuptoolsDeprecationWarning: License classifiers are deprecated.
      !!

              ********************************************************************************
              Please consider removing the following classifiers in favor of a SPDX license expression:

              License :: OSI Approved :: MIT License

              See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
              ********************************************************************************

      !!
        self._finalize_license_expression()
      src/pyaudio/device_api.c:9:10: fatal error: 'portaudio.h' file not found
          9 | #include "portaudio.h"
            |          ^~~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/cc' failed with exit code 1

      hint: This error likely indicates that you need to install a library that provides "portaudio.h" for `pyaudio@0.2.14`
  help: `pyaudio` (v0.2.14) was included because `pipecat-dictation` (v0.1.0) depends on `pipecat-ai[local]` (v0.0.82) which depends on `pyaudio`
```

**Comment by dtran320** [comment]
I ran into this as well. For me,

```bash
brew install portaudio
```

Then re-running `uv run bot-realtime-api.py` worked on `MacOS Sequoia 15.6`.
